DROP TABLE IF EXISTS INVENTORY; 
CREATE TABLE IF NOT EXISTS INVENTORY (ID INT, NAME VARCHAR, QUANTITY INT);
INSERT INTO INVENTORY VALUES(1, 'banana', 150);
INSERT INTO INVENTORY VALUES(2, 'orange', 154);
